version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5431:5431

  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - get_raw_data
    ports:
      - 8000:8000
    env_file:
      - .env

  get_raw_data:
    build: .
    command: python ./get_raw_data.py
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db


volumes:
  postgres_data:

